### PR TITLE
Pull request fix issue #73

### PR DESCRIPTION
**Pull request by jamespfarrell**
This pull request fixes [this issue](https://github.com/stuartmemo/theresas-sound-world/issues/73) , which I found [by way of this issue](https://github.com/stuartmemo/sympathetic-synth/issues/4)

I can re-build and create another pull request for the sympathetic synth once this one has gone through.

Please let me know if you think there is a better way to fix this of course, and thanks for all your hard work! :)

James

### CODE REVIEW

**Comment by stuartmemo** [comment]
Amazing! Thanks a lot. Any chance you could change the double quotes to single ones. Just so it's consistent. Thanks!

**Comment by jamespfarrell** [comment]
Yes I can do that

**Comment by jamespfarrell** [comment]
I actually changed it to used the existing isObject function - what I should have done, had I seen it in the first place.

**Comment by stuartmemo** [comment]
@jamespfarrell Nice one, thanks a lot! 🎹

**Pull request merged**
